
name: Build
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AZURE_SQL_CONNECTIONSTRING: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
      APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
      FORUM_API: ${{ secrets.FORUM_API }}
      RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      EDAMAM_API_ID: ${{ secrets.EDAMAM_API_ID }} 
      EDAMAM_API_KEY: ${{ secrets.EDAMAM_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pip
        run: python -m pip install --upgrade pip
      
      - name: Install all
        run: pip install -r requirements.txt

      - name: Run forum unit tests
        run: pytest api/test/forum_test.py

      - name: Run authentication unit tests
        run: pytest api/test/authentication_test.py

  build-and-deploy-main-app:

    name: Build Docker image of main app and deploy 
    runs-on: ubuntu-latest
    needs: forum-pytest
    # env:
    #   AZURE_WEBAPP_NAME: <your-app-name>
    #   GHCR_USERNAME: ${{ github.actor }}
    #   GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    permissions:
      contents: read
      packages: write
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # - name: Build Docker image
    #   working-directory: ./api/forum_api
    #   run: docker build -t fitness-planner-forum .
      
    # - name: Run PyTest
    #   run: docker run fitness-planner-forum pytest app_test.py

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: api/Dockerfile
        push: true
        tags: ghcr.io/brian-mak/workout-buddy-main:latest
        build-args: |
          "AZURE_SQL_CONNECTIONSTRING=${{ secrets.AZURE_SQL_CONNECTIONSTRING }}"
          "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}"
          "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}"
          "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}"
          "APP_SECRET_KEY=${{ secrets.APP_SECRET_KEY }}"
          "FORUM_API=${{ secrets.FORUM_API }}"
          "RAPID_API_KEY=${{ secrets.RAPID_API_KEY }}"
          "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}"
          "OPENAI_KEY=${{ secrets.OPENAI_KEY }}"
          "EDAMAM_API_ID=${{ secrets.EDAMAM_API_ID }}"
          "EDAMAM_API_KEY=${{ secrets.EDAMAM_API_KEY }}"
      
    # - name: Azure login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Restart Azure Container
    #   run: |
    #     az container restart --name $AZURE_WEBAPP_NAME --resource-group <your-resource-group-name>

    