
name: Build
on: [push]
jobs:
  forum-api-test:
    needs: python-formatting
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AZURE_SQL_CONNECTIONSTRING: ${{ AZURE_SQL_CONNECTIONSTRING }}
      APP_SECRET_KEY: ${{ APP_SECRET_KEY }}
      FORUM_API: ${{ FORUM_API }}
      RAPID_API_KEY: ${{ RAPID_API_KEY }}
      YOUTUBE_API_KEY: ${{ YOUTUBE_API_KEY }}
      OPENAI_KEY: ${{ OPENAI_KEY }}
      EDAMAM_API_ID: ${{ EDAMAM_API_ID }} 
      EDAMAM_API_KEY: ${{ EDAMAM_API_KEY }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install all
        run: pip install -r api/requirements.txt
      
      - name: Run unit tests
        run: pytest api/forum_api/app_test.py
  
  build-and-deploy-forum-api:
    
    name: Build Docker image of forum API and deploy 
    runs-on: ubuntu-latest
    needs: forum-api-test
    # env:
    #   AZURE_WEBAPP_NAME: <your-app-name>
    #   GHCR_USERNAME: ${{ github.actor }}
    #   GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    steps:
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./forum_api/Dockerfile
        push: true
        tags: ghcr.io/brian-mak/fitness-planner-forum:latest
        build-args: |
          AZURE_CONNECTION_STRING=${{ secrets.AZURE_CONNECTION_STRING }}
      
    # - name: Azure login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Restart Azure Container
    #   run: |
    #     az container restart --name $AZURE_WEBAPP_NAME --resource-group <your-resource-group-name>