
name: Build
on: [push]
jobs:
  run-pytest:
    name: Run Pytests for Main Application
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AZURE_SQL_CONNECTIONSTRING: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
      APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
      FORUM_API: ${{ secrets.FORUM_API }}
      RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      EDAMAM_API_ID: ${{ secrets.EDAMAM_API_ID }} 
      EDAMAM_API_KEY: ${{ secrets.EDAMAM_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pip
        run: python -m pip install --upgrade pip
      
      - name: Install all
        run: pip install -r requirements.txt
# add this below
      - name: Run forum unit tests
        run: pytest api/test/forum_test.py

      - name: Run authentication unit tests
        run: pytest api/test/authentication_test.py

  run-workout-managment-API-pytest:
    name: Run Pytests for Workout Management API 
    runs-on: ubuntu-latest
    env:
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AZURE_SQL_CONNECTIONSTRING: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
      APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
      FORUM_API: ${{ secrets.FORUM_API }}
      RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      EDAMAM_API_ID: ${{ secrets.EDAMAM_API_ID }} 
      EDAMAM_API_KEY: ${{ secrets.EDAMAM_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pip
        run: python -m pip install --upgrade pip
      
      - name: Install all
        run: pip install -r workout_management_microservice/requirements.txt
# add this below

      - name: Install Microsoft ODBC
        run: sudo ACCEPT_EULA=Y apt-get install msodbcsql18 -y

      - name: Run routes unit tests
        run: pytest workout_management_microservice/tests/test_routes.py

  run-microservice-test:
    name: Test Connectivity of Microservices 
    runs-on: ubuntu-latest
    needs: [run-pytest, run-workout-managment-API-pytest]
    env:
      FORUM_API: ${{ secrets.FORUM_API }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pip
        run: python -m pip install --upgrade pip
      
      - name: Install Flask
        run: pip install flask

      - name: Install requests
        run: pip install requests
      
      - name: Install pytest
        run: pip install pytest
  
      - name: Run microservice tests
        run: pytest api/test/microservice_test.py

  build-and-deploy:

    name: Build Docker image, Test and Push to GHCR
    runs-on: ubuntu-latest
    needs: run-microservice-test
    # env:
    #   AZURE_WEBAPP_NAME: <your-app-name>
    #   GHCR_USERNAME: ${{ github.actor }}
    #   GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
    permissions:
      contents: read
      packages: write
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        file: api/Dockerfile
        tags: workout-buddy-main
    
    - name: Test
      run: |
        docker run --rm workout-buddy-main pytest test/forum_test.py
        docker run --rm workout-buddy-main pytest test/microservice_test.py
    # test authentication in future

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: api/Dockerfile
        push: true
        tags: ghcr.io/brian-mak/workout-buddy-main:latest
        build-args: |
          "AZURE_SQL_CONNECTIONSTRING=${{ secrets.AZURE_SQL_CONNECTIONSTRING }}"
          "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}"
          "AUTH0_CLIENT_SECRET=${{ secrets.AUTH0_CLIENT_SECRET }}"
          "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}"
          "APP_SECRET_KEY=${{ secrets.APP_SECRET_KEY }}"
          "FORUM_API=${{ secrets.FORUM_API }}"
          "RAPID_API_KEY=${{ secrets.RAPID_API_KEY }}"
          "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}"
          "OPENAI_KEY=${{ secrets.OPENAI_KEY }}"
          "EDAMAM_API_ID=${{ secrets.EDAMAM_API_ID }}"
          "EDAMAM_API_KEY=${{ secrets.EDAMAM_API_KEY }}"
      
    # - name: Azure login
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Restart Azure Container
    #   run: |
    #     az container restart --name $AZURE_WEBAPP_NAME --resource-group <your-resource-group-name>

    